# Generated by Django 3.1.7 on 2021-05-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zadanie1_app', '0001_initial'),
    ]

    operations = [
    ]
